import React, { useState, useCallback } from 'react';
import {
  View,
  StyleSheet,
  Text,
  Switch,
  ScrollView,
  SafeAreaView,
  TouchableOpacity,
  Alert,
  Platform,
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { useAppLock } from '../../contexts/AppLockContext';
import { useFinance } from '../../contexts/FinanceContext';
import { COLORS } from '../../lib/constants';
import { formatMonth } from '../../lib/format';
import { Card } from '../../components/ui/Card';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export default function SettingsScreen() {
  const { isBiometricEnabled, setBiometricEnabled, biometricType, isEnrolled } = useAppLock();
  const { transactions, monthlyIncome, monthlyExpense } = useFinance();
  const [exporting, setExporting] = useState(false);

  const authTypeName = biometricTypeToString(biometricType);

  const handleExportPDF = useCallback(async () => {
    setExporting(true);
    try {
      const currentMonth = new Date();
      const monthLabel = formatMonth(currentMonth.toISOString());
      const rows = transactions.map(
        (tx) =>
          `<tr>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${new Date(tx.date).toLocaleDateString()}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${tx.category}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${tx.type}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; text-align: right; color: ${tx.type === 'income' ? '#10B981' : '#EF4444'};">$${tx.type === 'income' ? '' : '-'}${tx.amount.toFixed(2)}</td>
          </tr>`
      ).join('');

      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, system-ui, sans-serif; padding: 32px; color: #0f172a; }
            h1 { font-size: 24px; margin-bottom: 4px; }
            .subtotal { font-size: 16px; margin-bottom: 16px; color: #64748b; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; padding: 8px 12px; background: #f8fafc; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; border-bottom: 2px solid #e2e8f0; }
            .footer { text-align: center; font-size: 12px; color: #64748b; margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; }
          </style>
        </head>
        <body>
          <h1>${monthLabel} Report</h1>
          <div class="subtotal">
            Income: $${monthlyIncome.toFixed(2)} | Expenses: $${monthlyExpense.toFixed(2)}
          </div>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Type</th>
                <th style="text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>${rows || '<tr><td colspan="4" style="text-align: center; padding: 24px; color: #64748b;">No transactions</td></tr>'}</tbody>
          </table>
          <div class="footer">Generated by CashBook • ${new Date().toLocaleString()}</div>
        </body>
        </html>
      `;

      if (Platform.OS === 'web') {
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          printWindow.document.write(html);
          printWindow.document.close();
          printWindow.print();
        }
        return;
      }

      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri);
      }
    } catch (err) {
      Alert.alert('Export Failed', 'Could not generate PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  }, [transactions, monthlyIncome, monthlyExpense]);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar style="dark" />
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <Text style={styles.title}>Settings</Text>
        </View>

        {/* Security Section */}
        <Text style={styles.sectionTitle}>Security</Text>
        <Card style={styles.card}>
          <View style={styles.settingRow}>
            <View style={styles.settingInfo}>
              <Text style={styles.settingTitle}>App Lock</Text>
              <Text style={styles.settingSubtitle}>
                {isEnrolled
                  ? `${authTypeName} authentication`
                  : 'No biometric enrolled'}
              </Text>
            </View>
            <Switch
              value={isBiometricEnabled}
              onValueChange={(val) => {
                if (!isEnrolled) {
                  Alert.alert('Not Available', 'No biometric authentication is enrolled on this device.');
                  return;
                }
                setBiometricEnabled(val);
              }}
              trackColor={{ false: COLORS.border, true: COLORS.accent + '40' }}
              thumbColor={isBiometricEnabled ? COLORS.accent : COLORS.textSecondary}
              disabled={!isEnrolled}
            />
          </View>
        </Card>

        {/* Export Section */}
        <Text style={styles.sectionTitle}>Data</Text>
        <Card style={styles.card}>
          <TouchableOpacity
            style={styles.actionItem}
            onPress={handleExportPDF}
            disabled={exporting}
          >
            <Text style={styles.actionText}>Export Monthly Report (PDF)</Text>
            <Text style={styles.actionIcon}>{exporting ? '...' : '>'}</Text>
          </TouchableOpacity>
        </Card>

        {/* About Section */}
        <Text style={styles.sectionTitle}>About</Text>
        <Card style={styles.card}>
          <View style={styles.aboutRow}>
            <Text style={styles.aboutLabel}>Version</Text>
            <Text style={styles.aboutValue}>1.0.0</Text>
          </View>
          <View style={styles.aboutRow}>
            <Text style={styles.aboutLabel}>Platform</Text>
            <Text style={styles.aboutValue}>
              {Platform.OS === 'ios' ? 'iOS' : Platform.OS === 'android' ? 'Android' : 'Web'}
            </Text>
          </View>
          <View style={styles.aboutRow}>
            <Text style={styles.aboutLabel}>Storage</Text>
            <Text style={styles.aboutValue}>SQLite (Local)</Text>
          </View>
        </Card>
      </ScrollView>
    </SafeAreaView>
  );
}

function biometricTypeToString(type: number): string {
  const LocalAuthentication = require('expo-local-authentication');
  switch (type) {
    case LocalAuthentication.AuthenticationType.FACIAL_RECOGNITION:
      return 'Face';
    case LocalAuthentication.AuthenticationType.FINGERPRINT:
    case LocalAuthentication.AuthenticationType.IRIS:
      return 'Fingerprint';
    default:
      return 'Biometric';
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  header: {
    paddingBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.text,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 24,
    marginBottom: 8,
  },
  card: {
    padding: 0,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  settingInfo: {
    flex: 1,
  },
  settingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text,
  },
  settingSubtitle: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  actionText: {
    fontSize: 16,
    color: COLORS.text,
  },
  actionIcon: {
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  aboutRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  aboutLabel: {
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  aboutValue: {
    fontSize: 16,
    color: COLORS.text,
    fontWeight: '500',
  },
});
